# Exploratory Data Analysis with SQL

## Importing Libraries

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing

import seaborn as sns #statist graph package
import matplotlib.pyplot as plt #plot package
import pandasql as ps #sql package

plt.style.use('bmh')

# Reading the dataset

In [2]:
df = pd.read_csv('dataisbeautiful_posts.csv', low_memory=False)
df

,id,title,score,author,author_flair_text,removed_by,total_awards_received,awarders,created_utc,full_link,num_comments,over_18
0,ll1p9h,Wordcloud of trending video titles on YouTube ...,1,OmarZiada,OC: 1,NaN,0.0,[],1613473961,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
1,ll1o4h,Wordcloud of trending videos on YouTube in the...,1,OmarZiada,OC: 1,moderator,0.0,[],1613473829,https://www.reddit.com/r/dataisbeautiful/comme...,1,False
2,ll15gx,Immunization in India. Source: https://niti.go...,1,Professional_Napper_,NaN,moderator,0.0,[],1613471541,https://www.reddit.com/r/dataisbeautiful/comme...,1,False
3,ll0iup,How to quickly estimate the impact of players ...,1,Viziball,NaN,automod_filtered,0.0,[],1613468624,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
4,ll0g9a,How to quickly estimate the impact of players ...,1,Viziball,NaN,moderator,0.0,[],1613468281,https://www.reddit.com/r/dataisbeautiful/comme...,2,False
...,...,...,...,...,...,...,...,...,...,...,...,...
190848,pqbdl,Infosthetics seems like it belongs here.,15,magiclamp,NaN,NaN,NaN,NaN,1329282849,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
190849,pqav2,Time lapse of every nuclear detonation from 19...,9,th3sousa,NaN,NaN,NaN,NaN,1329282160,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
190850,pq922,Wavii.,13,ddshroom,NaN,NaN,NaN,NaN,1329279777,https://www.reddit.com/r/dataisbeautiful/comme...,2,False
190851,ppx09,An interactive representation of Pres. Obamas ...,21,zanycaswell,NaN,NaN,NaN,NaN,1329265203,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
190852,ppvl7,A map showing the geographical distribution of...,45,zanycaswell,NaN,NaN,NaN,NaN,1329263456,https://www.reddit.com/r/dataisbeautiful/comme...,5,False

In [3]:
df.sample(5)

,id,title,score,author,author_flair_text,removed_by,total_awards_received,awarders,created_utc,full_link,num_comments,over_18
4818,k7kesl,HCQ effect on covid when administered early.,1,andy34p,NaN,moderator,0.0,[],1607219051,https://www.reddit.com/r/dataisbeautiful/comme...,4,False
89777,8i65x5,Imma just leave this here,1,Jacob_Stacy,NaN,NaN,NaN,NaN,1525874202,https://www.reddit.com/r/dataisbeautiful/comme...,1,False
157385,3mburg,Browser Tech Support Helpline - 0800-279-6226 ...,1,jenniefernandes,NaN,NaN,NaN,NaN,1443184707,https://www.reddit.com/r/dataisbeautiful/comme...,1,False
55925,cwq980,Relative CO2 emission compared to power genera...,1,hokkos,NaN,NaN,0.0,NaN,1567023639,https://www.reddit.com/r/dataisbeautiful/comme...,2,False
26644,gge50d,"Create stunning, animated visualisations as ea...",1,VolcanicWolf,NaN,moderator,0.0,[],1589025034,https://www.reddit.com/r/dataisbeautiful/comme...,2,False

In [4]:
df.head(5)

,id,title,score,author,author_flair_text,removed_by,total_awards_received,awarders,created_utc,full_link,num_comments,over_18
0,ll1p9h,Wordcloud of trending video titles on YouTube ...,1,OmarZiada,OC: 1,NaN,0.0,[],1613473961,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
1,ll1o4h,Wordcloud of trending videos on YouTube in the...,1,OmarZiada,OC: 1,moderator,0.0,[],1613473829,https://www.reddit.com/r/dataisbeautiful/comme...,1,False
2,ll15gx,Immunization in India. Source: https://niti.go...,1,Professional_Napper_,NaN,moderator,0.0,[],1613471541,https://www.reddit.com/r/dataisbeautiful/comme...,1,False
3,ll0iup,How to quickly estimate the impact of players ...,1,Viziball,NaN,automod_filtered,0.0,[],1613468624,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
4,ll0g9a,How to quickly estimate the impact of players ...,1,Viziball,NaN,moderator,0.0,[],1613468281,https://www.reddit.com/r/dataisbeautiful/comme...,2,False

In [5]:
df.tail(5)

,id,title,score,author,author_flair_text,removed_by,total_awards_received,awarders,created_utc,full_link,num_comments,over_18
190848,pqbdl,Infosthetics seems like it belongs here.,15,magiclamp,NaN,NaN,NaN,NaN,1329282849,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
190849,pqav2,Time lapse of every nuclear detonation from 19...,9,th3sousa,NaN,NaN,NaN,NaN,1329282160,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
190850,pq922,Wavii.,13,ddshroom,NaN,NaN,NaN,NaN,1329279777,https://www.reddit.com/r/dataisbeautiful/comme...,2,False
190851,ppx09,An interactive representation of Pres. Obamas ...,21,zanycaswell,NaN,NaN,NaN,NaN,1329265203,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
190852,ppvl7,A map showing the geographical distribution of...,45,zanycaswell,NaN,NaN,NaN,NaN,1329263456,https://www.reddit.com/r/dataisbeautiful/comme...,5,False

In [6]:
print("Data shape: ", df.shape)

Data shape:  (190853, 12)

## Getting a feel of the dataset

Let's run basic dataframe exploratory commands

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 190853 entries, 0 to 190852
Data columns (total 12 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   id                     190853 non-null  str
 1   title                  190852 non-null  str
 2   score                  190853 non-null  int64
 3   author                 190853 non-null  str
 4   author_flair_text      28845 non-null   str
 5   removed_by             20744 non-null   str
 6   total_awards_received  65146 non-null   float64
 7   awarders               54478 non-null   str
 8   created_utc            190853 non-null  int64
 9   full_link              190853 non-null  str
 10  num_comments           190853 non-null  int64
 11  over_18                190853 non-null  bool
dtypes: bool(1), float64(1), int64(3), str(7)
memory usage: 16.2 MB

In [8]:
df.describe()

               score  total_awards_received   created_utc   num_comments
count  190853.000000           65146.000000  1.908530e+05  190853.000000
mean      176.016159               0.013109  1.512494e+09      27.604732
std      1951.936524               0.589425  6.822624e+07     213.236378
min         0.000000               0.000000  1.329263e+09       0.000000
25%         1.000000               0.000000  1.463862e+09       1.000000
50%         1.000000               0.000000  1.518662e+09       2.000000
75%         4.000000               0.000000  1.576576e+09       5.000000
max    116226.000000              93.000000  1.613474e+09   18801.000000

In [9]:
df.isnull().sum().sort_values(ascending=False)

removed_by               170109
author_flair_text        162008
awarders                 136375
total_awards_received    125707
title                         1
author                        0
id                            0
score                         0
created_utc                   0
full_link                     0
num_comments                  0
over_18                       0
dtype: int64

## Removed data

In [10]:
q1 = """SELECT
            removed_by,
            COUNT(distinct id) as number_of_removed_posts
        FROM df
        WHERE removed_by IS NOT NULL
        GROUP BY removed_by
        ORDER BY 2 DESC"""

grouped_df = ps.sqldf(q1, locals())
grouped_df

         removed_by  number_of_removed_posts
0         moderator                    14789
1           deleted                     2948
2  automod_filtered                     1553
3            reddit                     1453
4            author                        1